### ISSUE TITLE
Add a model exporter for NIF files

### ISSUE THREAD

**Issue by darkf** [niftools/pyffi#41]
@niftools/pyffi-reviewer 

## Issue Overview 
It would be nice if niftoaster could export NIF files to a more standard model format, such as OBJ or FBX.

This would serve both as a good example of using pyffi for NIF processing, as well as testing and using NIF files. (In particular, I am having unrelated issues with some OBJs exported from Blender, and this would help test that.)

### Pyffi Version Info
Any

### Platform information
Any

**Comment by neomonkeus** [comment]
OBJ is an archaic format which we are actively phasing out support for across the niftools projects.
Additionally we can't support direct conversion processors as that is against the EULA

**Comment by darkf** [comment]
What do you mean by "Additionally we can't support direct conversion processors as that is against the EULA"?

Nifskope exported OBJ (and, well, you could use another format) directly, and NIF is a file format, there is no EULA. There are freely redistributable NIF files.

**Comment by neomonkeus** [comment]
The following post describes the stance on the how we can't support direct asset format conversion - http://niftools.sourceforge.net/forum/viewtopic.php?f=1&t=17#wrap. Even with the use case you have suggested we won't be providing this as a supported feature.

As for nifskope we have not supported it since 1.1.3.

**Comment by Iloei** [comment]
Ok, but is not a format issue, and not an EULA issue - that is a content issue.

Copyright on files that nifskope can handle can be a documentation issue (if people are abusing nifskope to break copyright, you should have a "do not do this" blurb prominently displayed - sort of like the FBI warning that you see on devices that can read and record movie content - except you would be taking more responsibility than people are taking in that case (because there the warning is embedded in the content and not on the device)). But the mere possibility that people can misuse the tool is no reason to prevent the tool from existing.

Every useful thing can be misused, and the only way to be sure to prevent misuse is to prevent all use.

**Comment by neomonkeus** [comment]
The scope of Pyffi is a file read/write library, not an inter-format conversion tool. The previous comment is the official Niftools stance on this matter. This issue is being locked as this feature will not be investigated any further. Thank you for your contribution.
